name: Pull Request
on: [ push ]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Dependencies
      run: yarn
    - name: Lint
      run: yarn lint
    - name: Test Suite
      run: yarn test
    - name: Build
      run: yarn build
